# Generated by Django 5.1.5 on 2025-01-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rideevent",
            options={"ordering": ["created_at"]},
        ),
    ]
