# Generated by Django 5.1.5 on 2025-01-26 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_alter_rideevent_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="pickup_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
