# Generated by Django 5.1.5 on 2025-01-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_ride_pickup_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="pickup_location",
        ),
    ]
