# Generated by Django 5.1.5 on 2025-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_remove_ride_pickup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="dropoff_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
